name: CITest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps: 
    - uses: actions/checkout@master
    - name: Runa one-line sctips
      run: echo "hello world!"
    - name: Login to dockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Mutli line
      run: |
        echo '${{ secrets.DOCKERHUB_USER }}'\n
        for dir in */;do ls -la $dir/DockerFiles;done
    - name: Curl list
      run: | 
         curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ayushchatur/ARCworkflowPOC/pulls/2/files | grep filename | awk -F ':' '{print $2}' |  awk -F '/' '{print $1 }' | uniq | grep bc_*

