name: CITest
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    name: Code Checkout
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps: 
    - uses: actions/checkout@master
    - name: Runa one-line sctips
      run: echo "hello world!"