name: CITest
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - rearch
jobs:
  build:
    name: Code Checkout
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps: 
    - uses: actions/checkout@master
    - name: Runa one-line sctips
      run: echo "hello world!"
  DockerHub:
    name: Login to dockerHub
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    environment: 
      name: test
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: PR NUMBER
        run: | 
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        env: 
          PR_NUM: $PR_NUMBER
      - name: echo PR
        run:  echo $PR_NUM

